from __future__ import annotations

import json
from pathlib import Path

from app.main import app


def main() -> None:
    # Export the OpenAPI spec generated by FastAPI, so FE can mock and stay consistent.
    spec = app.openapi()

    out_path = Path(__file__).resolve().parents[1] / "openapi.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(spec, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")


if __name__ == "__main__":
    main()

